### ISSUE TITLE
Be able to set targets

### ISSUE THREAD

**Issue by corradio** [corradio/polynomial#117]
> This would enable us to tie the KPIs to our goals, for example 50k free API DAU or 40k app DAU, and see how far we are from these numbers. Maybe this can be done in the KPI sheets as a little hack (showing a target line), but it would also be nice to have it visualized as a little component indicating how much we are off the target.

This would enable to visualise health:
> Aggregations: This is a more abstract idea, but since we already have 25+ charts on the KPI sheet, it might be worth thinking about some aggregations /ways of summarising this information. Like a metric / health status for how we are performing on key areas: KPI activity, SoMe and Website.

**Comment by corradio** [comment]
cc @jbdietrich @mathiasGM target can now be set per metric (just hit "edit" to set it).
Feel free to let me know if you have other ideas on how to visualise this.

<img width="624" alt="image" src="https://github.com/corradio/polynomial/assets/1655848/ca14d702-6725-4f04-bbc5-76ae507cf613">

**Comment by mathiasGM** [comment]
Hi Oli, 
Thanks for adding this great feature! We actually did something very similar on the Emu quality dashboard, so I think the way you have visualized it makes perfect sense! 
![Screenshot 2024-04-10 at 16 51 38](https://github.com/corradio/polynomial/assets/33517196/eb3390ce-1b53-470a-b3fe-814aab71fb40)
