### ISSUE TITLE
make initdb not working on fresh install

### ISSUE THREAD

**Issue by madsnedergaard** [corradio/polynomial#187]
**Problem:**

I am getting an error when trying to run Poetry commands due to the static assets. Don't know enough about Django to just fix it myself :)

**Steps to reproduce:**
1. Clone repository
2. `poetry install`, `yarn`
3. Try running `make initdb`

![Screenshot 2024-07-10 at 07 44 30](https://github.com/corradio/polynomial/assets/3296643/de580a67-afe6-41fc-807e-89bfe120f605)

**Comment by corradio** [comment]
Can you try ‘poetry run python manage.py collectstatic’ ? This will create
a manifest file for all the static assets with proper version hashes.
I realize that the code is not optimally set up, as an import during
database migration shouldn’t cause an import of static assets. I’ll fix
this when I’m back!

Olivier

**Comment by madsnedergaard** [comment]
That works, thanks - and enjoy your vacation ;)
