### ISSUE TITLE
Impossible to use float values for BigQuery source

### ISSUE THREAD

**Issue by pierresegonne** [corradio/polynomial#196]
## Description

When trying to setup a BigQuery source, if the `value` columns returns a float, the parsing fails with the following error:

`Expected data from column 'value' to be a number. Received str instead.`

Casting to int fixes the issue, but it would be nicer if one had the freedom to use either data types

**Comment by corradio** [comment]
BigQuery returns decimal values as string. We now convert them in python instead. This will be more robust. Tested locally.

**Comment by corradio** [comment]
@pierresegonne can you confirm this fixed the issue?

**Comment by pierresegonne** [comment]
All systems nominal!
